### PR TITLE
Custom Labels APIs demonstration using public dog dataset

### PR DESCRIPTION
**Pull request by gptamab**
*Issue #, if available:*
Rekognition Custom Label datamanagement apis

*Description of changes:*
Rekognition Custom Label data management apis demonstration using public dog dataset

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ConnorKirk** [comment]
Thanks for submitting a PR @gptamab 

I have some general feedback

1. Please could you rename the notebook to be consistent with the other files (i.e. `custom-object-detection-using-rekognition-custom-labels-api.ipynb`)
2. The images referenced in the notebook don't work. I believe this is because the files are not included in the PR. Please could you add them. I suggest containing them a directory in `custom-labels/media` to keep consistency with the other samples.
3. I'm not able to comment on individual lines (file is too large), but there are a number of empty cells. Please could you remove them.

**Comment by gptamab** [comment]
Thank you @ConnorKirk 
1. Renamed the notebook to custom-object-detection-using-rekognition-custom-labels-api.ipynb
2. create a directory custom-labels/media and uploaded the screenshots. Also changed the reference in the notebook.
3. Removed the empty cells

**Review by ConnorKirk — APPROVED** [review]
LGTM me. Thanks for the contribution.

**Review by matteofigus — CHANGES_REQUESTED** [review]
Hi, thanks for your contribution, good stuff!

I have a couple of concerns:
1) Can you modify the image where you initialise the custom labels to obfuscate the actual bucket name you created in your account? This is to prevent s3 bucket spoofing.
2) I looked into the webpage hosting the dataset but I couldn't immediately find any documentation related to licensing. We should use the dataset only if that's allowed for re-distribution, did you find any documentation about that?
3) I see that where we download the data, it's hosted in an external domain and using `http` rather than `https`. This again may present some security problems, perhaps a solution would be to host it in a s3 public bucket we own (if the license permits re-distribution as mentioned before) so that we can ensure the customer downloads the content using `https` from a bucket that cannot be spoofed. If that's a route we want to pursue, with @ckp we can help (we have some public buckets in all regions that are approved for similar usage).

**Comment by gptamab** [comment]
Updated the Image for initializing the custom labels

**Review by matteofigus — APPROVED** [review]
Thanks, LGTM

**Pull request merged**
